-- Generated by Oracle SQL Developer Data Modeler 21.2.0.183.1957
--   at:        2021-11-04 21:54:05 PKT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE books (
    book_id           VARCHAR2(25 CHAR) NOT NULL,
    author_first_name VARCHAR2(25 CHAR) NOT NULL,
    author_last_name  VARCHAR2(25 CHAR) NOT NULL,
    rating            INTEGER
);

ALTER TABLE books ADD CONSTRAINT books_pk PRIMARY KEY ( book_id );

CREATE TABLE patrons (
    patrons_id     NUMBER NOT NULL,
    last_name      VARCHAR2(25 CHAR) NOT NULL,
    first_name     VARCHAR2(25 CHAR) NOT NULL,
    street_address VARCHAR2(40 CHAR),
    city           VARCHAR2(25 CHAR),
    state          VARCHAR2(2 CHAR),
    zip            VARCHAR2(10 CHAR),
    location       unknown 
--  ERROR: Datatype UNKNOWN is not allowed 

);

ALTER TABLE patrons ADD CONSTRAINT patrons_pk PRIMARY KEY ( patrons_id );

CREATE TABLE transactions (
    transaction_id     NUMBER NOT NULL,
    transaction_date   DATE NOT NULL,
    transaction_type   NUMBER NOT NULL,
    book_id            NUMBER,
    patron_id          NUMBER,
    books_book_id      VARCHAR2(25 CHAR) NOT NULL,
    patrons_patrons_id NUMBER NOT NULL
);

ALTER TABLE transactions ADD CONSTRAINT transactions_pk PRIMARY KEY ( transaction_id );

ALTER TABLE transactions
    ADD CONSTRAINT transactions_books_fk FOREIGN KEY ( books_book_id )
        REFERENCES books ( book_id );

ALTER TABLE transactions
    ADD CONSTRAINT transactions_patrons_fk FOREIGN KEY ( patrons_patrons_id )
        REFERENCES patrons ( patrons_id );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             3
-- CREATE INDEX                             0
-- ALTER TABLE                              5
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   1
-- WARNINGS                                 0
